version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123123
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 123123123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123123123
    depends_on:
      - db
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db